# Setup args
init_msg: "Iudex Gundyr gym. Please make sure you start at the `Cemetry of Ash` bonfire!\n
Please make sure your keyboard settings are correct!"
cam_setup_orient: [0.378, 0.926, 0]

# StateSpace coordinate boxes
coordinate_box_low:  [110., 540., -73., -3.1416]
coordinate_box_high: [190., 640., -55., 3.1416]
# Player and boss stats boxes
player_max_hp: 454
player_max_sp: 95
boss_max_hp: 1037
# Spawn info
bonfire: "Cemetery of Ash"